services:
  telegraf:
    # image: telegraf:latest
    build:
      context: telegraf
      dockerfile: Dockerfile
    container_name: telegraf
    restart: unless-stopped
    volumes:
      # - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_ETC=/hostfs/etc
      - INFLUXDB_TOKEN
      - INFLUXDB_URL
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET
      - HOSTNAME
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # network_mode: host
    group_add: 
    - 988

  influxdb3:
    image: quay.io/influxdb/influxdb3-core:latest
    ports:
      - "8183:8181"  # Map host port 8181 to container port 8181
    volumes:
      - influxdb3-data:/var/lib/influxdb3  # Persist data
    command:
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    environment:
      - INFLUXDB3_AUTH_TOKEN=${INFLUXDB_TOKEN}  # Set admin token
    healthcheck:
      test: ["CMD", "curl", "-sSf", "--header", "Authorization: Token ${INFLUXDB_TOKEN}", "http://localhost:8181/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  grafana:
    build: 
      context: grafana
      dockerfile: Dockerfile
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      
    volumes:
      - grafana-data:/var/lib/

    ports:
      - "3006:3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


volumes:
  influxdb3-data:
  grafana-data: