{
 "title": "System Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "SHOW TAG VALUES FROM system WITH KEY = \"host\""
    }
   }
  ]
 },
 "panels": [
  { "title": "${hostname}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "CPU 1-5-15 Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \nlast(\"load1\") / max(\"n_cpus\") AS \"load_1\",\nlast(\"load5\") / max(\"n_cpus\") AS \"load_5\",\nlast(\"load15\") / max(\"n_cpus\") AS \"load_15\"\nFROM \"system\" \nWHERE $timeFilter AND (\"host\"::tag =~ /^$hostname$/)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"health_status\") AS \"health_status\"\nFROM \"docker_container_health\"\nWHERE time >= now() - 10m\nGROUP BY time(1h), \"container_name\"::tag"
    }
   ]
  },
  {
   "title": "Top Memory Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT \nlast(\"usage_percent\") AS usage, \n\"container_name\"\nFROM \"docker_container_mem\" \nWHERE $timeFilter AND \"host\" = '${hostname}'\nGROUP BY \"container_name\"",
     "rawSql": "SELECT \"host\", MAX(\"time\"), AVG(\"usage_percent\") AS usage, \"container_name\" FROM \"docker_container_cpu\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"host\" = '${hostname}' GROUP BY \"container_name\", \"host\" HAVING usage > 0"
    }
   ]
  },
  {
   "title": "Top CPU Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "SELECT \nlast(\"usage_percent\") AS usage, \n\"container_name\"\nFROM \"docker_container_cpu\" \nWHERE $timeFilter AND \"host\" = '${hostname}'\nGROUP BY \"container_name\"",
     "rawSql": "SELECT \"host\", MAX(\"time\"), AVG(\"usage_percent\") AS usage, \"container_name\" FROM \"docker_container_cpu\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"host\" = '${hostname}' GROUP BY \"container_name\", \"host\" HAVING usage > 0"
    }
   ]
  },
  {
   "title": "Docker Stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "measurement": "docker",
     "query": "SELECT last(\"n_containers_running\") AS running,  last(\"n_containers_paused\") AS paused, last(\"n_containers_stopped\") AS stopped FROM \"docker\" WHERE (\"host\"::tag =~ /^$hostname$/) AND $timeFilter",
     "rawSql": "SELECT \"n_containers_running\", \"n_containers_stopped\", \"n_containers_paused\", \"host\" FROM \"docker\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"host\" = '${hostname:singlequotes}' ORDER BY \"time\" ",
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "System Resources Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "2",
     "measurement": "mem",
     "query": "SELECT last(\"used_percent\") AS memory FROM \"mem\" WHERE (\"host\"::tag =~ /^$hostname$/) AND $timeFilter",
     "rawSql": "SELECT \"time\", \"used_percent\" AS \"RAM\", \"host\" FROM \"mem\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND host = ${hostname:singlequote} ORDER BY \"time\" DESC ",
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "dataset": "iox",
     "limit": "2",
     "measurement": "disk",
     "query": "SELECT last(\"used_percent\") AS disk FROM \"disk\" WHERE (\"host\"::tag =~ /^$hostname$/) AND $timeFilter",
     "rawSql": "SELECT \"time\", \"used_percent\" AS \"DISK\" FROM \"disk\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND host = ${hostname:singlequote} ORDER BY \"time\" DESC LIMIT 1",
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "System Resources Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "measurement": "system",
     "query": "SELECT last(\"used_percent\") AS memory_used FROM \"mem\" WHERE (\"host\"::tag =~ /^$hostname$/) AND $timeFilter",
     "rawSql": "SELECT \"time\", \"used_percent\" AS \"RAM\", \"host\" FROM \"mem\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND host = ${hostname:singlequote} ORDER BY \"time\" DESC ",
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "dataset": "iox",
     "measurement": "mem",
     "query": "SELECT \"used_percent\" AS \"disk_used\" FROM \"disk\" WHERE (\"host\"::tag =~ /^$hostname$/) AND $timeFilter",
     "rawSql": "SELECT \"time\", \"used_percent\" AS \"DISK\" FROM \"disk\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND host = ${hostname:singlequote} ORDER BY \"time\" DESC LIMIT 1",
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "measurement": "system",
     "query": "SELECT \"uptime_format\" FROM \"system\" WHERE (\"host\"::tag =~ /^$hostname$/) AND $timeFilter ORDER BY time DESC LIMIT 1",
     "rawSql": "SELECT \"uptime_format\" FROM \"system\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "CPU Load (per Core)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "iox",
     "measurement": "cpu",
     "query": "SELECT \"usage_system\" FROM \"cpu\" WHERE $timeFilter ORDER BY time DESC",
     "rawSql": "SELECT \r\n    DATE_BIN($__interval, \"time\") AS time,\r\n    MAX(\"usage_user\") AS usage_user,\r\n    \"host\",\r\n    \"cpu\"\r\nFROM \"cpu\"\r\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"host\" = ${hostname:singlequote} AND \"cpu\" != 'cpu-total'\r\nGROUP BY DATE_BIN($__interval, \"time\"), \"cpu\", \"host\"\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "CPU 1-5-15 Load",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 5, "y": 9 },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_load",
     "query": "SELECT \n    max(\"load1\") / max(\"n_cpus\") AS \"load_1\",\n    max(\"load5\") / max(\"n_cpus\") AS \"load_5\",\n    max(\"load15\") / max(\"n_cpus\") AS \"load_15\"\nFROM \"system\" \nWHERE (\"host\"::tag =~ /^$hostname$/) AND $timeFilter \nGROUP BY time($__interval) fill(null) \nORDER BY time DESC",
     "rawSql": "SELECT \r\n    DATE_BIN(INTERVAL '1 minute', time) AS _time,\r\n    AVG(usage_user) AS load_1,\r\n    host,\r\n    cpu\r\nFROM cpu\r\nWHERE time >= $__timeFrom AND time <= $__timeTo AND host = ${hostname:singlequote} AND cpu = 'cpu-total'\r\nGROUP BY _time, host, cpu\r\nORDER BY _time",
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Docker CPU Usage (Detailed)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "query": "SELECT \nmean(\"usage_percent\")\nFROM \"docker_container_cpu\"\nWHERE $timeFilter AND \"usage_percent\" > 0 AND (\"host\"::tag =~ /^$hostname$/)\nGROUP BY time($__interval), \"container_name\"",
     "rawSql": "SELECT \"host\", MAX(\"time\"), AVG(\"usage_percent\") AS usage, \"container_name\" FROM \"docker_container_cpu\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"host\" = '${hostname}' GROUP BY \"container_name\", \"host\" HAVING usage > 0"
    }
   ]
  },
  {
   "title": "Docker Memory Usage (Detailed)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "query": "SELECT \nmean(\"usage_percent\")\nFROM \"docker_container_mem\"\nWHERE $timeFilter AND \"usage_percent\" > 0 AND (\"host\"::tag =~ /^$hostname$/)\nGROUP BY time($__interval), \"container_name\"",
     "rawSql": "SELECT \"host\", MAX(\"time\"), AVG(\"usage_percent\") AS usage, \"container_name\" FROM \"docker_container_cpu\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"host\" = '${hostname}' GROUP BY \"container_name\", \"host\" HAVING usage > 0"
    }
   ]
  },
  {
   "title": "System Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "rawSql": "SELECT \r\n  DATE_BIN($__interval, \"time\") as _time, \r\n  \"used_percent\" AS \"memory\", \r\n  \"host\" \r\nFROM \"mem\" \r\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND host = ${hostname:singlequote} \r\nORDER BY _time DESC",
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "dataset": "iox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "rawSql": "SELECT \r\n  DATE_BIN($__interval, \"time\") as _time, \r\n  \"used_percent\" AS \"disk\", \r\n  \"host\" \r\nFROM \"disk\" \r\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND host = ${hostname:singlequote} \r\nORDER BY _time DESC",
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Docker Block IO (Read)",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "SELECT\n  DIFFERENCE(\"read_bytes\") AS \"read_bytes\"\nFROM (\n  SELECT\n    MAX(\"io_service_bytes_recursive_read\") AS \"read_bytes\"\n  FROM \"docker_container_blkio\"\n  WHERE $timeFilter AND (\"host\"::tag =~ /^$hostname$/)\n  GROUP BY time($__interval), \"container_name\" \n)\nWHERE \"read_bytes\" > 0\nGROUP BY \"container_name\" FILL(0)\n"
    }
   ]
  },
  {
   "title": "Docker Block IO (Write)",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "query": "SELECT\n  DIFFERENCE(\"write_bytes\") AS \"write_bytes\"\nFROM (\n  SELECT\n    MAX(\"io_service_bytes_recursive_write\") AS \"write_bytes\"\n  FROM \"docker_container_blkio\"\n  WHERE $timeFilter AND (\"host\"::tag =~ /^$hostname$/)\n  GROUP BY time($__interval), \"container_name\"\n)\nWHERE \"write_bytes\" > 0\nGROUP BY \"container_name\"\n"
    }
   ]
  }
 ]
}